# Generated by Django 5.2 on 2025-04-21 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('historique_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type_action', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('information_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_employe', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_assurance', models.CharField(blank=True, max_length=255, null=True)),
                ('ciin', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('objet', models.CharField(blank=True, max_length=255, null=True)),
                ('contenu', models.CharField(blank=True, max_length=255, null=True)),
                ('expediteur', models.CharField(blank=True, max_length=255, null=True)),
                ('destinataire', models.CharField(blank=True, max_length=255, null=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('statut', models.BooleanField()),
                ('historique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='data_info.historique')),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='data_info.information')),
            ],
        ),
        migrations.CreateModel(
            name='Compagnie_Assurance',
            fields=[
                ('compagnie_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_compagnie', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse_compagnie', models.CharField(blank=True, max_length=255, null=True)),
                ('email_compagnie', models.CharField(blank=True, max_length=255, null=True)),
                ('notifications', models.ManyToManyField(related_name='compagnies_assurance', to='data_info.notification')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('utilisateur_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('discriminator', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='information',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='data_info.utilisateur'),
        ),
    ]
