# Generated by Django 5.2 on 2025-04-21 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='discriminator',
            new_name='mot_de_passe',
        ),
    ]
