# Generated by Django 5.2 on 2025-04-21 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_info', '0002_rename_discriminator_utilisateur_mot_de_passe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='ciin',
            new_name='cin',
        ),
    ]
