# Generated by Django 5.2 on 2025-04-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_info', '0003_rename_ciin_information_cin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='statut',
        ),
    ]
