# Generated by Django 5.2 on 2025-04-28 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_info', '0006_information_email_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='compagnie_assurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informations', to='data_info.compagnie_assurance'),
        ),
        migrations.AlterField(
            model_name='compagnie_assurance',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='compagnies_assurance', to='data_info.notification'),
        ),
    ]
