apiVersion: v1
kind: Service
metadata:
  name: django-backend-service
spec:
  selector:
    app: django-backend
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30080 # Choisir un port entre 30000-32767
  type: NodePort
